#!/bin/bash

POPPLER_VERSION=${POPPLER_VERSION-0.69.0}
POPPLER_TARBALL_URL="https://poppler.freedesktop.org/poppler-${POPPLER_VERSION}.tar.xz"
TEMP_DIR=$(mktemp -d /tmp/poppler.XXXXXXXXXX)

#if ! [ -x "$(command -v xc)" ]; then
#  export DEBIAN_FRONTEND=noninteractive
#  apt-get update
#  apt-get install -y xz-utils
#fi

apt-get update
apt-get install -y xz-utils

echo "Serving files from /tmp on $PORT"
cd /tmp
python -m SimpleHTTPServer $PORT &

cd $TEMP_DIR
echo "Temp dir: $TEMP_DIR"

echo "Downloading $POPPLER_TARBALL_URL"
curl -L $POPPLER_TARBALL_URL | tar xJ

(
	cd poppler-${POPPLER_VERSION}
	apt-get install -y build-essential cmake
	cmake -DCMAKE_INSTALL_PREFIX=/tmp/poppler -DCMAKE_BUILD_TYPE=release -DENABLE_LIBOPENJPEG="none" -DBUILD_SHARED_LIBS=OFF 
	make install
)

cp /tmp/poppler/bin/pdftotext $1
